### ISSUE TITLE
Small fixes to Assets Table

### ISSUE THREAD

**Issue by bbtgnn** [dyne/interfacer-gui#101]
~~Two things~~ One thing to do:
- [x] ~~remove `console.log` introduced by previous pr~~ #99 
- [x] fix `Warning: Each child in a list should have a unique "key" prop.`

**Comment by bbtgnn** [comment]
Actually, there was no `console.log`: there's a `devLog` printing on line 129. @puria should be removed?
Otherwise I'll leave as it is

**Comment by puria** [comment]
@bbtgnn No #sticazzi devLog is fine (guess is something Ennio has implemented and only prints on dev environment e, BTW Ennio is on high fever, so will not interact today I guess 🥰) if you have other doubts lemme know
