### ISSUE TITLE
[Minor fix] Solve `Warning: validateDOMNesting(...): <tr> cannot appear as a child of <div>.`

### ISSUE THREAD

**Issue by bbtgnn** [dyne/interfacer-gui#111]
## The problem

When using `BrTable`, this error appears
```
Warning: validateDOMNesting(...): <tr> cannot appear as a child of <div>.
```
This is `BrTable` component
https://github.com/dyne/interfacer-gui/blob/16295b9635ff6c3e1fedf4c8410a8c2da4dfe388/components/brickroom/BrTable.tsx#L11-L23

## Solutions
- We remove tailwind table utilities (such as `table-header-group`) and replace with semantic html elements
- Otherwise, we remove all the `tr` and `td` used and replace them with divs. 

I would go with the first solution, as I think it's also better for accessibility.
What do you say? @puria @phoebus-84

**Comment by puria** [comment]
Please go forward with divs, that are more responsive and maybe in the future we don't want to have tabular data, but cards.
So prefer to move on `div` politics in all places.
