### ISSUE TITLE
"Interfacer" vs "Fabcity OS" branding

### ISSUE THREAD

**Issue by andrea-dintino** [dyne/interfacer-gui#173]
Currently on the GUI we use both names, this is confusing for the user. The question of which one to use is indeed non trivial and should be discussed with the consortium. In any case, we need to stick to one branding overall on the website.

**Comment by puria** [comment]
@me watching this ;p

**Comment by andrea-dintino** [comment]
We are picking "Interfacer", case closed! :-)
