### ISSUE TITLE
Improve BrDisplayUser

### ISSUE THREAD

**Issue by puria** [dyne/interfacer-gui#98]
Let's refactor BrDisplayUser,
good comments are written in https://github.com/dyne/interfacer-gui/pull/97#issue-1389016043

**Comment by bbtgnn** [comment]
I'm adding another suggestion: `BrDisplayUser` could be split in two components (naming to be reviewed).
- `BrDisplayUser` that is just the div with image and info text
  - (In order to easily reuse just the design)
- `BrDisplayUserLink` : adds a wrapper <link><a> around `BrDisplayUser`

**Comment by puria** [comment]
please go ahead with that <3 che 💣
